"""Constants for IPL data analysis."""

# Deliveries CSV Column Names
MATCH_ID = 'match_id'
INNING = 'inning'
BATTING_TEAM = 'batting_team'
BOWLING_TEAM = 'bowling_team'
OVER = 'over'
BALL = 'ball'
BATSMAN = 'batsman'
NON_STRIKER = 'non_striker'
BOWLER = 'bowler'
IS_SUPER_OVER = 'is_super_over'
WIDE_RUNS = 'wide_runs'
BYE_RUNS = 'bye_runs'
LEGBYE_RUNS = 'legbye_runs'
NOBALL_RUNS = 'noball_runs'
PENALTY_RUNS = 'penalty_runs'
BATSMAN_RUNS = 'batsman_runs'
EXTRA_RUNS = 'extra_runs'
TOTAL_RUNS = 'total_runs'
PLAYER_DISMISSED = 'player_dismissed'
DISMISSAL_KIND = 'dismissal_kind'
FIELDER = 'fielder'

# Matches CSV Column Names
MATCH_ID_COL = 'id'
SEASON = 'season'
CITY = 'city'
DATE = 'date'
TEAM1 = 'team1'
TEAM2 = 'team2'
TOSS_WINNER = 'toss_winner'
TOSS_DECISION = 'toss_decision'
RESULT = 'result'
DL_APPLIED = 'dl_applied'
WINNER = 'winner'
WIN_BY_RUNS = 'win_by_runs'
WIN_BY_WICKETS = 'win_by_wickets'
PLAYER_OF_MATCH = 'player_of_match'
VENUE = 'venue'
UMPIRE1 = 'umpire1'
UMPIRE2 = 'umpire2'
UMPIRE3 = 'umpire3'

# File Paths
MATCHES_FILE = 'data/matches.csv'
DELIVERIES_FILE = 'data/deliveries.csv'
